
pipelines:
  - name: test
    steps:
      - name: testBashStep
        type: Bash
        configuration:
          nodePool: centOS_8
        execution:
          onExecute:
            - echo "hello"
